# Generated by Django 4.2.1 on 2023-08-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertmodel',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
