# Generated by Django 4.2.1 on 2023-08-30 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_groupmodel_creator'),
        ('alert', '0002_alertmodel_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertmodel',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_related', to='groups.groupmodel'),
        ),
    ]
