# Generated by Django 4.2.1 on 2023-06-24 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_groupmodel_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmodel',
            name='user_id',
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
