# Generated by Django 4.2.1 on 2023-08-28 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import process.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0004_groupmodel_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captureImage', models.ImageField(null=True, upload_to=process.models.get_upload_path)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_capturer', to='groups.groupmodel')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_taker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
