# Generated by Django 4.2.1 on 2023-07-05 13:12

import attendances.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_groupmodel_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='present_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='present_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoPath', models.ImageField(blank=True, null=True, upload_to=attendances.models.get_upload_path)),
                ('date', models.DateField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groupmodel')),
            ],
        ),
    ]
