# Generated by Django 4.2.2 on 2023-08-18 15:44

import attendances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0002_alter_attendance_present_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='photoPath',
            field=models.ImageField(upload_to=attendances.models.get_upload_path),
        ),
    ]
